name: Draft release

on:
  workflow_call:
    inputs:
      version-file-path:
        default: ""
        required: false
        type: string
  workflow_dispatch:
    inputs:
      version-file-path:
        default: ""
        required: false
        type: string


concurrency:
  group: "${{ github.workflow }}"

env:
  GH_TOKEN: "${{ github.token }}"

permissions: {}

jobs:
  bump-version:
    name: Bump version
    environment: release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      env:
        EVENT: ${{ toJSON(github.event) }}
      run: |
        echo "${EVENT}" | jq
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: true
    - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        python-version: "3.14"
    - name: Get old version
      id: old-version
      run: |
        VERSION=$(gh release list -L 1 --json name | jq -r '.[0].name // "00.0b0"')
        echo version=${VERSION} >> "${GITHUB_OUTPUT}"
        echo "${VERSION}"
